### ISSUE TITLE
Adding a copy link button

### ISSUE THREAD

**Issue by PhattOZ** [gouravkhunger/nextjs-birthday-wish#15]
I'm thinking of adding a copy link button, so we don't have to manually copy the address. 

- the "copy link" button besides "<- create a wish" button
- notified "link copied" when clicked. I'm thinking of changing the button style instead of pop up alert.

**Comment by chaitanyks** [comment]
I will start work on that.

**Comment by gouravkhunger** [comment]
Thanks for this feature request! I see @chaitanyks has already made a PR for that, kudos on that :)

But, as a general ethic, please do wait for project maintainers to give a green signal before starting on a project. In the future it can happen with you that you are working on a big feature and someone else pops in and completes it before you, and gets his contribution.

So, it's better to wait for maintainer's prompt and then start, so that we can assign that issue to you otherwise someone else would get done with their PR :)

**Comment by PhattOZ** [comment]
Yea…

**Comment by gouravkhunger** [comment]
I feel sorry for you @PhattOZ :(

**Comment by gouravkhunger** [comment]
Hey @PhattOZ, chitinyks has stopped working on this and has closed this PR. I think I can assign this to you.

What you should implement is:

- Just as [another project of mine](https://github.com/gouravkhunger/nextjs-strikeit), add a small note like this:
    <img width="403" alt="image" src="https://user-images.githubusercontent.com/46792249/135762791-88eead42-47ae-4f6a-b993-f0232139a70d.png">

    Stating- "Pressing Go will copy your wish link that can be shared".

- Implement the logic to copy the link to the clipboard something like this, in the input event.
    ```js
        navigator.clipboard.writeText("This will be copied!")
    ```

- As in the strikeit project, show a blue message that the Link is copied, something like this, when Go button is pressed:
    <img width="151" alt="image" src="https://user-images.githubusercontent.com/46792249/135762879-742f689c-f693-4913-99b5-37e97a9fed26.png">


Are you willing to take this up?

**Comment by PhattOZ** [comment]
Absolutely! I’ve read through the PR discussion and I think I have some idea.
I think having a button on the preview page might look a bit nicer though.
Should I try
- button on preview page. Hidden when open directly from a URL
first or
- copy on the go

**Comment by gouravkhunger** [comment]
If you are sure you can implement "button on preview page. Hidden when open directly from a URL" without changing the URL scheme, then I would prefer that. 

But if in any case, if you think this isn't feasible, you can always go for the 2nd option :)

**Comment by siddhantdixit** [comment]
@gouravkhunger  I would like to work on this issue. Can u assign it to me?

**Comment by gouravkhunger** [comment]
Hi @siddhantdixit thanks for your interest, but currently @PhattOZ hasn't replied if he would take up the issue or not. If he denies, then this issue will be assigned to you :) 

Thanks!

**Comment by PhattOZ** [comment]
Alright, I’ll take this up. Will keep you posted!

**Comment by gouravkhunger** [comment]
Great!

**Comment by gouravkhunger** [comment]
hey @PhattOZ do sync the repo because we introduced a completely new feature that has changes the code structure, but it is amazing!

**Comment by gouravkhunger** [comment]
Otherwise there would be massive merge conflicts xD

**Comment by PhattOZ** [comment]
It's quite a big feature indeed. There're still one or two things I wanted to add. Could you please suggest how should I keep the repo in sync?

**Comment by gouravkhunger** [comment]
Did you actually start working on this issue? If not, you can fork and clone it again and it will be synced.

But if you are mid-way, you can make the PR and I will take care of the merge conflicts, either ways there will be new things to learn as it was my first time dealing with conflicts :)

**Comment by PhattOZ** [comment]
Oh so PR doesn't have to be the completed version? This is also new for me.

**Comment by gouravkhunger** [comment]
You can make a PR with the copy link feature implemented.

I was just saying that in this case, since there was a code refactor, and many lines have changed, been removed and added. Now if you make PR, git will give a merge conflict that you want to change lines that don't even exist.

But that's what the repository maintainers have to look forward to. You can go ahead with making the PR with feature implemented and I will take care of the merge conflicts :)

**Comment by PhattOZ** [comment]
I've implemented the copy link button with style changes and the copy functionality. However, I'm still working on the direct URL and some clicking event problem. Should I create the PR now?

**Comment by gouravkhunger** [comment]
I would suggest to make the PR only when the direct URL doesn't show the copy button and navigation from Home page shows the copy button. Otherwise, if at a later point of time we come to know that this feature isn't implementable, it won't be hard to take time closing the PR and making a new one with the other workaround.

**Comment by avneesh0612** [comment]
anyone working on this 👀 @gouravkhunger

**Comment by gouravkhunger** [comment]
Yes @avneesh0612 , @PhattOZ is working :)
